version: '3.3'
services:
    influxdb:
        container_name: influxdb
        volumes:
            - '/storage/internal/database/influxdb:/var/lib/influxdb'
        ports:
            - '8086:8086'
        restart: unless-stopped
        labels:
            - com.centurylinklabs.watchtower.enable=false
        image: 'influxdb:1.8.4'