version: '3.3'
services:
    portainer-ce:
        container_name: portainer
        ports:
            - '8000:8000'
            - '9000:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        image: portainer/portainer-ce