version: '3.3'
services:
    watchtower:
        container_name: watchtower
        environment:
            - 'WATCHTOWER_SCHEDULE=0 0 6 * * *'
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_NOTIFICATIONS=gotify
            - 'WATCHTOWER_NOTIFICATION_GOTIFY_URL='
            - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        image: containrrr/watchtower