version: '3.3'
services:
    samba:
        container_name: samba
        network_mode: host
        ports:
            - '139:139'
            - '445:445'
            - '137:137/udp'
            - '138:138/udp'
        volumes:
            - '/storage:/storage'
        environment:
            - NMBD=true
        restart: unless-stopped
        image: dperson/samba