version: '3.3'
services:
    samba:
        container_name: samba
        network_mode: host
        ports:
            - '139:139'
            - '445:445'
            - '137:137/udp'
            - '138:138/udp'
        volumes:
            - '/storage:/storage'
        environment:
            - NMBD=true
            - TZ='Europe/Paris'
        command: ' -n -S -g "map to guest = Bad User" -w WORKGROUP -s "storage;/storage;yes;no;no;${SMB_USERNAME};none;${SMB_USERNAME};Media share" -u "${SMB_USERNAME};${SMB_PASSWORD}"'
        restart: unless-stopped
        image: dperson/samba