version: '3.3'
services:
    linuxserver:
        container_name: radarr
        ports:
            - '7878:7878'
        volumes:
            - '/storage/internal/config/radarr/:/config'
            - '/storage:/storage'
            - '/storage/downloads:/downloads'
        restart: unless-stopped
        image: ghcr.io/linuxserver/radarr